name: Helix CI
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */12 * * *'

jobs:
  Merge_PR_CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip.exec=true
    - name: Run All Tests
      run: mvn -q -fae test
    - name: Print Tests Results
      run: .github/scripts/printTestResult.sh
      if: ${{ success() || failure() }}
    - name: Upload to Codecov
      run: bash <(curl -s https://codecov.io/bash)
      if: ${{ github.event_name == 'push' && (success() || failure()) }}
